### ISSUE TITLE
Deskbar logo change

### ISSUE THREAD

**Issue by MacaronZone** [augiedoggie/TrackRunner#1]
Hi auggiedoggie,
Sorry to get your attention in this way but I'm not sure how else to contact you. About 10 years ago, you created, or at least knew of and referenced, a tool that would allow someone to change the leaf logo on the haiku deskbar, but the links I've found no longer exist. I was wondering if this was a tool that would even work anymore, and if you think it may, I would love a link to it. It's also great that haiku has gotten to such a stable place that theming can be a priority. Thanks for all of your work.

**Comment by augiedoggie** [comment]
> Hi auggiedoggie, Sorry to get your attention in this way but I'm not sure how else to contact you.

You mean like contacting me on the forums where the message was originally posted :angry: 

> I was wondering if this was a tool that would even work anymore

No
