### ISSUE TITLE
Add needed build requirements to ReadMe.md

### ISSUE THREAD

**Issue by humdingerb** [augiedoggie/TrackRunner#4]
Configuring with cmake says:

```
-- Could NOT find Sphinx (missing: SPHINX_BUILD_EXE) 
CMake Warning at CMakeLists.txt:15 (message):
  Sphinx was not found.  You will not be able to build the user guide.
```

I installed "sphinx" with pkgman, but still get that message.

Maybe also mention a debug version can be built with `cmake -DCMAKE_BUILD_TYPE=Debug` (for ignoramus like me...)

**Comment by humdingerb** [comment]
The issue is still valid, but I just found that the sphinx package is empty...

**Comment by humdingerb** [comment]
Apparently, I needed `sphinx_python310` which turn drew in a few dozen more packages. Sigh, python.... :)

**Comment by humdingerb** [comment]
Still doesn't build the user guide:
```
Extension error:
Could not import extension sphinx.builders.epub3 (exception: No module named 'snowballstemmer')
Assets/CMakeFiles/UserGuide.dir/build.make:74: recipe for target 'UserGuide/index.html' failed
make[2]: *** [UserGuide/index.html] Error 2
CMakeFiles/Makefile2:117: recipe for target 'Assets/CMakeFiles/UserGuide.dir/all' failed
make[1]: *** [Assets/CMakeFiles/UserGuide.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
```

I'll stop spamming this ticket now, and wait for the added instructions to the ReadMe.

**Comment by augiedoggie** [comment]
For the moment you can fix this by installing the `snowballstemmer_python310` package.  I'll have to see if it's supposed to be a dependency of `sphinx_python310` at some point or update the ReadMe.  I also noticed there are some minor things that need to be fixed with the new version of sphinx(like the svg logo not showing at the top of the page).

Edit: I also had to `export LC_ALL=C` in my shell for some reason but I don't think that's a problem for you.

**Comment by humdingerb** [comment]
snowballstemmer fails to install:

```
 2 ɸ> pkgman install snowballstemmer_python310
Refreshing repository "Haiku" failed  0%: Operation not supported
Refreshing repository "HaikuPorts" failed  0%: Operation not supported
The following changes will be made:
  in system:
    install package snowballstemmer_python310-2.2.0-1 from repository HaikuPorts
Continue? [yes/no] (yes) : yes
*** Failed to download package snowballstemmer_python310: Operation not supported
```

Python, gotta love it... :}

Personally, I stick with straight HTML documentation. If you want, I can convert the user guide to HTML...

**Comment by augiedoggie** [comment]
That's strange, I installed it last night while testing sphinx.  There seems to be something wrong with your Haiku install.

**Comment by humdingerb** [comment]
I'm currently trying to binary search a network thruput regression I'm experiencing. I've up-, down-, and aroundgrading for some time now. I just retried and now it's working. So to get the dependencies:

`pkgman install cmake snowballstemmer_python310 sphinx_python310`
